Comment IR code for bound checking on window_shape
Because it somehow conflicts with conditional expressions, producing
this error:

RuntimeError: PHI node entries do not match predecessors!